FROM node:14-alpine as develop-stage

WORKDIR /app
COPY package*.json ./

RUN apk add --no-cache yarn && \
    yarn --version

COPY . .

# build stage
FROM develop-stage as build-stage
RUN yarn build

# production stage
FROM nginx:1.15.7-alpine as production-stage
COPY --from=build-stage /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]