FROM node:20-alpine as develop-stage

WORKDIR /app

COPY package.json ./

RUN apk add --no-cache yarn && \
    yarn --version

RUN yarn install

COPY . .

# build stage
FROM develop-stage as build-stage
RUN yarn build

# production stage
FROM nginx:stable-alpine as production-stage
COPY --from=build-stage /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]