version: "3"

services:
  backend:
    build: ./api
    ports:
      - "5000:5000"
    depends_on:
      - database

  database:
    image: mongo
    expose:
      - "27017"
    ports:
      - "27017:27017"

  frontend:
    build: ./client/blog
    ports:
      - "8080:8080"
    depends_on:
      - database
      - backend