version: "3"

services:
  backend:
    build: ./api
    ports:
      - "5000:5000"
    depends_on:
      - database
    environment:
      - MONGO_URI=mongodb://pentagram_db:27017/pentagram_db

  database:
    image: mongo
    container_name: pentagram_db
    expose:
      - "27017"
    ports:
      - "27017:27017"

  frontend:
    build:
      context: ./client/blog
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - database
      - backend