version: "3"

services:
  backend:
    container_name: backend_container
    build: ./api
    ports:
      - "5000:5000"
    depends_on:
      - database
    environment:
      - MONGO_URI=mongodb+srv://Hilal:1234@hilitopage.hti7p3k.mongodb.net/

  database:
    container_name: database_container
    image: mongo
    container_name: pentagram_db
    expose:
      - "27017"
    ports:
      - "27017:27017"

  frontend:
    container_name: frontend_container
    build:
      context: ./client/blog
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - database
      - backend