FROM python:3.9

WORKDIR /app
COPY . .

RUN apt-get update && apt-get install -y python3-pip

RUN pip install -r requirements.txt

EXPOSE 5000

ENV MONGO_URI=mongodb://pentagram_db:27017/pentagram_db
#burayı dinlemiyor

CMD ["python", "app.py"]